baseURL: http://google.devops.delivery/
languageCode: en-us
title: GCP Sandboxes

# https://themes.gohugo.io/themes/hugo-book/
theme: hugo-book

menu:
  after:
    - name: "Sandboxes on GitHub"
      url: "https://github.com/agilestacks/google-stacks"
      weight: 10
    - name: "Components on GitHub"
      url: "https://github.com/agilestacks/google-components"
      weight: 20

params:
  BookSection: "*"
  BookToC: false

  cloudShell:
    url: https://ssh.cloud.google.com/cloudshell/editor
    image: gcr.io/superhub/cloud-shell

  sandboxesGit:
    url: https://github.com/agilestacks/google-stacks
    branch: main

  sandboxes:
    - title: GKE cluster with Demo application
      btn: Deploy GKE + Demo App
      name: gke-with-demo-app
    - title: GKE cluster with Anthos Service Mesh and Demo application
      btn: Deploy GKE + ASM + Demo App
      name: gke-anthos-with-demo-app
    - title: Just GKE cluster
      btn: Deploy empty GKE cluster
      name: gke-empty-cluster
    - title: Web Server VM with SQL Server
      btn: Deploy Web Server VM + Cloud SQL
      name: vm-php-web-server
    - title: Cloud SQL instance with k6.io load test
      btn: Deploy Cloud SQL + Load Test
      name: cloud-sql-perftest
    - title: Cloud Composer with a sample ETL pipeline to move data from Cloud Storage to BigQuery
      btn: Deploy Composer + BigQuery
      name: composer-demo-app
