name: Sync Sandboxes README

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "content/**.md"
      - "!content/**index.md"

jobs:
  sync:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-sync
    steps:
      - name: "Checkout This repo"
        uses: actions/checkout@v3
        with:
          path: main

      - name: "Checkout Sandboxes repo"
        uses: actions/checkout@v3
        with:
          repository: agilestacks/google-stacks
          path: sandboxes

      - name: "Update README files"
        run: |
          find main/content -type f -name '*.md' ! -name '*index.md' -exec sh -c '
            filename=$(basename "$1")
            readme="sandboxes/${filename%.md}"
            mkdir -p "$readme"
            cp -r "$1" "$readme/README.md"
            sed -i -e "/^---$/,/^---$/d" "$readme/README.md"
          ' sh {} \;

      - name: "Prepare git info"
        id: git_info
        run: |
          echo "::set-output name=git_sha::$(echo $GITHUB_SHA | cut -c-7)"
          echo "::set-output name=user_name::${{ github.event.head_commit.author.name || github.event.sender.name }}"
          echo "::set-output name=user_email::${{ github.event.sender.login }}@users.noreply.github.com"

      - name: "Push updates"
        run: |
          git -C sandboxes config user.name ${{ steps.git_info.outputs.user_name }}
          git -C sandboxes config user.email ${{ github.event.head_commit.author.email || steps.git_info.outputs.user_email }}
          git -C sandboxes add .
          git -C sandboxes commit -m "Update READMEs ${{ github.repository }}@${{ steps.git_info.outputs.git_sha }}"
          git -C sandboxes push
